apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-discord-bot
  template:
    metadata:
      labels:
        app: dev-discord-bot
    spec:
      containers:
      - name: dev-discord-bot
        image: gcr.io/mercurial-feat-328320/dev-discord-bot:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        env:
        
          - name: discordToken
            valueFrom:
              secretKeyRef:
                name: dev-discord-bot-secrets
                key: DISCORD_TOKEN

          - name: bearerPublicAPI
            valueFrom:
              secretKeyRef:
                name: dev-discord-bot-secrets
                key: BEARER_PUBLIC_API

          - name: dbString
            valueFrom:
              secretKeyRef:
                name: dev-discord-bot-secrets
                key: DB_STRING


