steps:

- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/dev-discord-bot:latest", "."]
 

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/dev-discord-bot:latest"]


- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s/dev
  - --image=gcr.io/$PROJECT_ID/dev-discord-bot:latest
  - --location=us-central1-a	
  - --cluster=dev-discord-bot