steps:

- name: "gcr.io/cloud-builders/docker"
  entrypoint: bash
  args: 
    - -c
    - |
        dockerbuild -t gcr.io/$PROJECT_ID/dev-discord-bot:latest --build-arg DISCORD_TOKEN=$$DEV_DISCORD_TOKEN --build-arg BEARER_PUBLIC_API=$$DEV_BEARER_PUBLIC_API --build-arg HOST=$$DEV_DISC_HOST --build-arg USER=$$DEV_DISC_USER --build-arg PASSWORD=$$DEV_DISC_PASSWORD --build-arg DATABASE=$$DEV_DISC_DATABASE .
  secretEnv: ['DEV_DISCORD_TOKEN', 'DEV_BEARER_PUBLIC_API', 'DEV_DISC_HOST', 'DEV_DISC_USER', 'DEV_DISC_PASSWORD', 'DEV_DISC_DATABASE']


- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/dev-discord-bot:latest"]


- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s/dev
  - --image=gcr.io/$PROJECT_ID/dev-discord-bot:latest
  - --location=us-central1-a	
  - --cluster=dev-discord-bot


  availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/DEV_DISCORD_TOKEN/versions/latest
    env: 'DEV_DISCORD_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/DEV_BEARER_PUBLIC_API/versions/latest
    env: 'DEV_BEARER_PUBLIC_API'
  - versionName: projects/$PROJECT_ID/secrets/DEV_DISC_HOST/versions/latest
    env: 'DEV_DISC_HOST'
  - versionName: projects/$PROJECT_ID/secrets/DEV_DISC_USER/versions/latest
    env: 'DEV_DISC_USER'
  - versionName: projects/$PROJECT_ID/secrets/DEV_DISC_PASSWORD/versions/latest
    env: 'DEV_DISC_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/DEV_DISC_DATABASE/versions/latest
    env: 'DEV_DISC_DATABASE'